#!/usr/bin/env bash
#
# Athrill2 application launcher
#   athrill_launcher
# Author: jtFuruhata
# Copyright (c) 2020 ETロボコン実行委員会, Released under the MIT license
# See LICENSE
#
if [ "$1" == "usage" ] || [ "$1" == "--help" ]; then
    echo "usage: athrill_launcher [check|stop] [left|l_app|right|r_app] <projName>"
    exit 0
fi

# unset/env option for etrobo env core
if [ "$1" == "unset" ]; then
    unset ETROBO_ATHRILL_CONFIG
    exit 0
elif [ "$1" == "env" ]; then
    mode_env="env"
    shift
else
    unset mode_env
fi

# default filenames for launcher
athrill2="$ETROBO_ATHRILL_WORKSPACE/athrill2"
memory_txt="$ETROBO_ATHRILL_SDK/common/memory.txt"
device_config_path="$ETROBO_ATHRILL_SDK/common"
target="$ETROBO_ATHRILL_WORKSPACE/asp"

#
# memory.txt hotfix
#
# @todo: this process has to move into build_athrill.sh
if [ -d "$ETROBO_ATHRILL_SDK" ] && [ ! -f "${memory_txt}.org" ]; then
    cp "$memory_txt" "${memory_txt}.org"
    cat $ETROBO_ATHRILL_SDK/common/memory.txt | sed -E 's/^(R[OA]M, 0x00[02]00000,) 512$/\1 2048/' > "${memory_txt}.tmp"
    rm "$memory_txt"
    cp "${memory_txt}.tmp" "$memory_txt"
    rm "${memory_txt}.tmp"
fi

# search & select a path to device_config.txt
# select priority: 
# 1. $ETROBO_HRP3_WORKSPACE/etroboc_common
# 2. $ETROBO_ATHRILL_WORKSPACE/etroboc_common
# 3. $ETROBO_ATHRILL_SDK/common
if [ -f "$ETROBO_HRP3_WORKSPACE/etroboc_common/device_config.txt" ]; then
    device_config_path="$ETROBO_HRP3_WORKSPACE/etroboc_common"
elif [ -f "$ETROBO_ATHRILL_WORKSPACE/etroboc_common/device_config.txt" ]; then
    device_config_path="$ETROBO_ATHRILL_WORKSPACE/etroboc_common"
fi
device_config_txt="$device_config_path/device_config.txt"

# course select
app_prefix=""
app_select="l_app"
sim_select="left"
if [ "$1" = "l" ] || [ "$1" = "left" ] || [ "$1" = "l_app" ] || [ "$1" = "l_" ]; then
    app_prefix="l_"
    shift
elif [ "$1" = "r" ] || [ "$1" = "right" ] || [ "$1" = "r_app" ] || [ "$1" = "r_" ]; then
    app_prefix="r_"
    app_select="r_app"
    sim_select="right"
    device_config_txt="$device_config_path/device_config_r.txt"
    shift
fi

# export the path to device_config.txt
export ETROBO_ATHRILL_CONFIG="$device_config_txt"

# start launcher
if [ -z "$mode_env" ]; then
    # check for already running
    if [ -f "$ETROBO_SIM_DIST/${app_select}.status" ]; then
        echo "[ athrill_launcher: $app_select is already running. ]"
        exit 1
    else
        touch "$ETROBO_SIM_DIST/${app_select}.status"
    fi

    # determine the target file
    projName="$1"
    if [ -z "$projName" ] && [ -f "$ETROBO_HRP3_WORKSPACE/currentapp" ]; then
        currentapp=`head -n 1 "$ETROBO_HRP3_WORKSPACE/currentapp"`
        projName=`echo $currentapp | sed -E "s/^app=|img=(.*)$/\1/"`
    fi
    target="${app_prefix}${projName}.asp"
    if [ ! -f "$ETROBO_SIM_DIST/$projName/$target" ]; then
        target="${projName}.asp"
    fi

    # invoke runner
    if [ -f "$ETROBO_SIM_DIST/$projName/$target" ]; then
        cd "$ETROBO_SIM_DIST/$projName"
        athrill_runner "$ETROBO_SIM_DIST/${app_select}.status" "$athrill2" "$memory_txt" "$device_config_txt" "$target" > $ETROBO_HRP3_WORKSPACE/test.log &
        echo "[ athrill_launcher: launch: $target ]"
        echo "[ athrill_launcher: runnerPID=$!  launcherPID=$$ ]"
    else
        echo "[ athrill_launcher: $target: file not exists. ]"
        exit 1
    fi
fi

