#!/usr/bin/env bash
#
# Athrill2 application thread runner
#   launch_runner.sh
# Author: jtFuruhata
# Copyright (c) 2020 ETロボコン実行委員会, Released under the MIT license
# See LICENSE
#
if [ "$1" == "usage" ] || [ "$1" == "--help" ]; then
    echo "usage: athrill_runner </path/to/status> </path/to/athrill2> </path/to/memory.txt> </path/to/device_config.txt> <appFileName>"
    exit 0
fi

status_file="$1"
athrill2="$2"
memory_txt="$3"
device_config_txt="$4"
target="$5"

trap "echo 'terminated.'; rm -f \"$status_file\"" EXIT

${athrill2} -c1 -m ${memory_txt} -d ${device_config_txt} -t -1 "$target" \
| consolepipe \
| while read line; do
    if [ "`echo $line | grep athrill_device_func_call=`" ]; then
        echo "athrill is booted up" >> "$status_file"
    fi
done
