#!/usr/bin/env bash
projName="`echo \"$1\" | grep ^app= | sed -E 's/^app=(.*)$/\1/'`"
if [ -z "$projName" ]; then
    projName=`cat "$ETROBO_HRP3_WORKSPACE/currentapp" | head -n 1 | sed -E "s/^app=|img=(.*)$/\1/"`
else
    shift
fi
proj="$ETROBO_HRP3_WORKSPACE/simdist/$projName"
btout="$proj/__ev3rt_bt_out"
btlog="$1"
echo "[ btcat: attempt to connect with Virtual BT on $projName ]"
while [ -z "`ls \"$proj\"` | grep ^__ev3rt_bt_out" ]; do
    sleep 0.1
done
sleep 1 # ToDo: magic number
while [ -z "`ls \"$proj\"` | grep ^__ev3rt_bt_out" ]; do
    sleep 0.1
done

if [ -z "$btlog" ]; then
    cat "$btout" 2>&1 # | grep -v "__ev3rt_bt_out: No such file or directory$"
    while [ "$?" != "0" ]; do
        sleep 0.1
        cat "$btout" 2>&1 # | grep -v "__ev3rt_bt_out: No such file or directory$"
    done
else
    cat "$btout" 2>&1 | grep -v "__ev3rt_bt_out: No such file or directory$" > "$proj/$btlog"
    while [ "$?" != "0" ]; do
        sleep 0.1
        cat "$btout" 2>&1 | grep -v "__ev3rt_bt_out: No such file or directory$" > "$proj/$btlog"
    done
fi
