#!/usr/bin/env bash
projName="`echo \"$1\" | grep ^app= | sed -E 's/^app=(.*)$/\1/'`"
if [ -z "$projName" ]; then
    if [ -f "$ETROBO_HRP3_WORKSPACE/currentapp" ]; then
        projName=`cat "$ETROBO_HRP3_WORKSPACE/currentapp" | head -n 1 | sed -E "s/^app=|img=(.*)$/\1/"`
    else
        projName="__race"
    fi
else
    shift
fi

sleep 1 # ToDo: magic number

proj="$ETROBO_HRP3_WORKSPACE/simdist/$projName"
btout="$proj/__ev3rt_bt_out"
btlog="$1"
timer=15
echo "[ btcat: attempt to connect with Virtual BT on $projName ]"
loop="loop"
while [ -n "$loop" ]; do
    if [ ! -p "$bt_out" ]; then
        unset loop
    else
        sleep 1
        timer=$(($timer - 1))
        if [ "$timer" == "0" ]; then
            unset loop
        fi
    fi
done
if [ "$timer" == "0" ]; then
    echo "[ btcat: Virtual BT not found ]"
    exit 1
fi

echo "[ btcat: connected with Virtual BT on $projName ]"

if [ -z "$btlog" ]; then
    cat "$btout" 2> /dev/null
else
    cat "$btout" > "$proj/$btlog" 2> /dev/null
fi
echo "[ btcat: terminated. ]"
