#!/usr/bin/env bash
projName="`echo \"$1\" | grep ^app= | sed -E 's/^app=(.*)$/\1/'`"
if [ -z "$projName" ]; then
    projName=`cat "$ETROBO_HRP3_WORKSPACE/currentapp" | head -n 1 | sed -E "s/^app=|img=(.*)$/\1/"`
fi
echo "$@" > "$ETROBO_SIM_DIST/$projName/__ev3rt_bt_in"
