#!/usr/bin/env bash
#
# fake wineconsole for nxtOSEK running on WSL
#
# (fake)wineconsole
#
# for etrobo environment Ver 1.00a.230423
# Copyright (c) 2023 jtLab, Hokkaido Information University
# by TANAHASHI, Jiro(aka jtFuruhata) <jt@do-johodai.ac.jp>
# Released under the MIT license
# https://opensource.org/licenses/mit-license.php
#

invoker="$1"
shift 1
if [ -z "`basename \"$invoker\" | grep .exe$`" ]; then
    invoker="$invoker.exe"
fi

"$invoker" "$@"
