#!/usr/bin/env bash
#
# SPIKE utility for SPIKE-RT
#
# spike
#
# for etrobo environment Ver 1.00a.260312
# Copyright (c) 2026 jtLab, Hokkaido Information University
# by TANAHASHI, Jiro(aka jtFuruhata) <jt@do-johodai.ac.jp>
# Released under the MIT license
# https://opensource.org/licenses/mit-license.php
#
# this script is intended to be sourced by etroboenv.sh, and also to be executed directly

# detect host OS
if [ -z "$ETROBO_OS" ]; then
    set -- $(./scripts/detect_host_os)
    ETROBO_OS="$1"
    if [ "$ETROBO_OS" == "win" ]; then
        ETROBO_OS_SUBSYSTEM="$2"
    fi
fi

# command recognition
unset command
if [ -n "$1" ]; then
    command="$1"
    shift
fi
if [ "$command" == "--help" ] || [ "$command" == "usage" ]; then
    echo "Usage: spike [options]"
    echo "Options:"
    echo "  unset   Unset environment variables"
    return 0
fi

#
# unset - unset environment variables
#
if [ "$command" = "unset" ]; then
    unset ETROBO_SPIKE_DRIVER
    unset ETROBO_SPIKE_DEVICE_MODE_ENUM
    unset ETROBO_SPIKE_DEVICE_ID_ENUM
    unset ETROBO_SPIKE_DEVICE_MODE
    unset ETROBO_SPIKE_DEVICE_BUS
    unset ETROBO_SPIKE_DEVICE_DEV
    unset ETROBO_SPIKE_DEVICE_ID
    exit 0
fi

#
# driver - check USB serial driver availability and set environment variables
#
if [ "$command" == "driver" ] || [ "$command" == "env" ]; then
    # check USB serial driver availability and set environment variables
    unset ETROBO_SPIKE_DRIVER
    if [ "$ETROBO_OS" == "win" ]; then
        if [ $(powershell.exe 'usbipd list' > /dev/null 2>&1; echo $?) -eq 0 ]; then
            export ETROBO_SPIKE_DRIVER="usbip-win"
        fi
    elif [ "$ETROBO_OS" == "mac" ]; then
        if [ -n "$(brew list --versions libusb)" ]; then
            export ETROBO_SPIKE_DRIVER="homebrew"
        fi
    else
        export ETROBO_SPIKE_DRIVER="debian"
    fi
    if [ -n "$ETROBO_SPIKE_DRIVER" ] && [ "$(lsusb)" != "127" ]; then
        export ETROBO_SPIKE_DRIVER="available"
    fi

    if [ "$1" == "check" ]; then
        if [ "$ETROBO_SPIKE_DRIVER" == "available" ]; then
            exit 0
        else
            exit 1
        fi
    fi
fi

# discover a connected SPIKE device and set environment variables
export ETROBO_SPIKE_DEVICE_MODE_ENUM=("DFU" "SPIKE App" "Pybricks")
export ETROBO_SPIKE_DEVICE_ID_ENUM=("0694:0008" "0694:0009" "0483:5740")
unset ETROBO_SPIKE_DEVICE_MODE
unset ETROBO_SPIKE_DEVICE_BUS
unset ETROBO_SPIKE_DEVICE_DEV
unset ETROBO_SPIKE_DEVICE_ID
device=$(IFS="|"; lsusb | grep -E "${ETROBO_SPIKE_DEVICE_ID_ENUM[*]}")
if [ -n "$device" ]; then
    export ETROBO_SPIKE_DEVICE_BUS=$(echo "$device" | awk '{print $2}')
    export ETROBO_SPIKE_DEVICE_DEV=$(echo "$device" | awk '{print $4}' | sed 's/://')
    export ETROBO_SPIKE_DEVICE_ID=$(echo "$device" | awk '{print $6}')
    index=0
    for dev in "${ETROBO_SPIKE_DEVICE_ID_ENUM[@]}"; do
        if [[ "$dev" == "$ETROBO_SPIKE_DEVICE_ID" ]]; then
            break
        fi
        index=$((index + 1))
    done
    export ETROBO_SPIKE_DEVICE_MODE=${ETROBO_SPIKE_DEVICE_MODE_ENUM[$index]}
fi

#
# device - show connected SPIKE device mode
if [ "$command" == "device" ]; then
    if [ -n "$ETROBO_SPIKE_DEVICE_MODE" ]; then
        echo "$ETROBO_SPIKE_DEVICE_MODE"
        exit 0
    else
        exit 1
    fi
fi
